// THE STUDENTS WILL TAKE THE BASIC 13 ALGO TEST ON THURSDAY

// ON TUESDAY GO OVER THE FUNDAMENTALS OF JS (LOOPS, IFS, VARIABLES, CONSOLE.LOG VS RETURN)

// ON WEDNESDAY GO OVER RIOT AND GO OVER SWAPPING AND NEEDING A TEMP VARIABLE TO DO THAT
// MAKE SURE TO GO OVER RIOT WALK!!!
