// THE STUDENTS WILL TAKE THE BASIC 13 ALGO TEST ON THURSDAY
// ON TUESDAY GO OVER THE FUNDAMENTALS OF JS (LOOPS, IFS, VARIABLES, CONSOLE.LOG VS RETURN)
// ON WEDNESDAY GO OVER SWAPS, IF STATEMENTS, FOR LOOPS
