// IMPLEMENT A METHOD TO PERFROM BASIC STRING COMPRESSION USING THE COUNTS OF REPEATED CHARS.
// FOR EXAMPLE, 'aabcccccaaa' would become 'a2b1c5a3'. IF THE 'COMPRESSED STRING' WOULD NOT 
// SMALLER THAN THE ORIGINAL, YOUR METHOD SHOULD RETURN THE ORIGINAL STRING.
// YOU CAN ASSUME THE STRING ONLY HAS UPPERCASE AND LOWERCASE LETTERS

function stringCompression(){
    
}