// TAKE A NUMBER COMING AND REVERSE IT
// DO NOT TURN THE NUMBER INTO STRING AND THEN REVERSE THE STRING
// ONLY ALLOW INTEGER TO BE TURNED INTO STRING FOR JUST THE STRING LENGTH




function reverseNum(num){
    var newnum = 0
    while(num > 0){
        // WE GET THE LAST DIGIT OF THE INCOMING NUMBER
        var lastDigit = num % 10;
        // FOR THE NEW NUMBER RETURNING, SHIFT NUMBER LEFT BY MULTIPLYING 10 AND THEN ADDING THE LAST DIGIT FROM PREVIOUS
        newnum = (newnum * 10) + lastDigit
        // SHIFT THE NUMBER RIGHT OF THE INCOMING NUMBER BY DIVIDING BY 10 AND THEN FLOORING IT
        num = Math.floor(num / 10)
    }
    console.log("LAST NEW NUM", newnum)
}


reverseNum(54321)